"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { requestJson } from "../../lib/client";

export default function AuthForm({ mode }: { mode: "login" | "register" | "recover" }) {
  const router = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [recoveryCode, setRecoveryCode] = useState(""); const [saved, setSaved] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const form = new FormData(event.currentTarget); const input: Record<string, unknown> = { email: form.get("email"), password: form.get("password") };
    if (mode === "register") Object.assign(input, { name: form.get("name"), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, consent: form.get("consent") === "on" });
    if (mode === "recover") input.recoveryCode = form.get("recoveryCode");
    try { const result = await requestJson<{ recoveryCode?: string }>(`/api/auth/${mode === "register" ? "register" : mode}`, "POST", input); if (result.recoveryCode) setRecoveryCode(result.recoveryCode); else { router.push("/dashboard"); router.refresh(); } } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <main className="auth-shell"><Link className="brand" href="/"><span className="brand-mark">◒</span> Идеальный год</Link><section className="auth-card">{recoveryCode ? <><p className="eyebrow">Доступ под вашим контролем</p><h1>Сохраните код восстановления</h1><p>Он позволит задать новый пароль, если вы забудете текущий. Код показывается один раз.</p><code className="recovery-code">{recoveryCode}</code><label className="check"><input type="checkbox" checked={saved} onChange={e => setSaved(e.target.checked)} />Я сохранил код в безопасном месте</label><button className="primary" disabled={!saved} onClick={() => { router.push(mode === "recover" ? "/login" : "/dashboard"); router.refresh(); }}>Продолжить</button></> : <><p className="eyebrow">Один шаг к себе</p><h1>{mode === "register" ? "Начните свой год" : mode === "recover" ? "Восстановление доступа" : "Рады вашему возвращению"}</h1><p className="muted">{mode === "register" ? "Создайте личный кабинет. Telegram можно подключить позже." : mode === "recover" ? "Введите код, который вы сохранили при регистрации." : "Войдите, чтобы продолжить свой маршрут."}</p><form onSubmit={submit}>{mode === "register" && <label>Как к вам обращаться?<input name="name" autoComplete="name" required minLength={2} maxLength={80} /></label>}<label>Email<input name="email" type="email" autoComplete="email" required maxLength={254} /></label><label>{mode === "recover" ? "Новый пароль" : "Пароль"}<input name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} required minLength={mode === "login" ? 1 : 12} maxLength={128} /></label>{mode !== "login" && <p className="fine-print">Не менее 12 символов. Можно использовать менеджер паролей.</p>}{mode === "recover" && <label>Код восстановления<input name="recoveryCode" autoComplete="off" required minLength={20} maxLength={100} /></label>}{mode === "register" && <label className="check"><input name="consent" type="checkbox" required /><span>Мне исполнилось 18 лет. Я согласен с <Link href="/privacy" target="_blank">условиями обработки данных</Link>. Организатор видит имя, email, задания и статусы выполнения; личные ответы и заметки ему не показываются.</span></label>}{error && <p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy ? "Подождите…" : mode === "register" ? "Создать аккаунт" : mode === "recover" ? "Задать новый пароль" : "Войти"}</button></form><p className="auth-links">{mode === "login" ? <><Link href="/register">Создать аккаунт</Link><Link href="/recover">Забыли пароль?</Link></> : <Link href="/login">Уже есть аккаунт? Войти</Link>}</p></>}</section></main>;
}
