"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Header from "./components/header";
import Wheel from "./components/wheel";
import { requestJson, statusLabels } from "../lib/client";
import { spheres, starterQuestions, labelForVariant, type Variant } from "../lib/domain";
import type { Member } from "../lib/session";
import type { Task } from "../lib/tasks";

type Snapshot = { id: string; scores: (number | null)[]; created_at: string };
type Data = { user: Member; task: Task | null; history: Task[]; snapshots: Snapshot[]; telegram: { available: boolean; connected: boolean; pending: { candidate_name: string } | null } };
type Tab = "today" | "plan" | "history" | "settings";
const profile = (user: Member) => ({ name: user.name, timezone: user.timezone, focus: user.focus, goal: user.goal, answers: user.answers, scores: user.scores, paused: user.paused });

export default function Dashboard() {
  const router = useRouter(); const [data, setData] = useState<Data | null>(null); const [draft, setDraft] = useState<ReturnType<typeof profile> | null>(null); const [tab, setTab] = useState<Tab>("today"); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [variant, setVariant] = useState<Variant>("normal"); const [note, setNote] = useState(""); const [telegramUrl, setTelegramUrl] = useState(""); const reportKey = useRef(crypto.randomUUID());
  const load = useCallback(async () => { const next = await requestJson<Data>("/api/dashboard"); setData(next); setDraft(profile(next.user)); setNote(next.task?.note ?? ""); setVariant((next.task?.variant as Variant) ?? "normal"); if (!next.user.onboarded) setTab("plan"); }, []);
  useEffect(() => { load().catch(e => setError(e.message)); }, [load]);
  async function action(fn: () => Promise<unknown>, success: string) { setError(""); setMessage(""); setBusy(true); try { await fn(); await load(); setMessage(success); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function saveProfile(event: FormEvent) { event.preventDefault(); await action(() => requestJson("/api/me", "PATCH", draft), "Маршрут сохранён. Изменение фокуса применяется к следующей задаче."); }
  async function report(result: string) { if (!data?.task) return; await action(() => requestJson(`/api/tasks/${data.task!.id}/report`, "POST", { result, variant, note }, { "Idempotency-Key": reportKey.current }), "Отчёт сохранён. Оценки сфер не изменились."); }
  if (!data || !draft) return <main className="loading"><p>{error || "Загружаем ваш кабинет…"}</p><a href="/login">Войти заново</a></main>;
  const user = data.user;
  return <><Header admin={user.role === "admin"} /><main className="workspace"><div className="page-heading"><div><p className="eyebrow">Личное пространство</p><h1>{user.name}, ваш следующий шаг</h1><p className="muted">Не нужно успевать всё. Выберите посильное на сегодня.</p></div><span className="date-pill">{new Intl.DateTimeFormat("ru", { day: "numeric", month: "long", timeZone: user.timezone }).format(new Date())}</span></div><div className="summary-grid"><article><span>Ваш фокус</span><strong>{user.focus}</strong></article><article><span>Выполнено</span><strong>{data.history.filter(t => t.status === "COMPLETED").length} <small>шагов</small></strong></article><article><span>Telegram</span><strong>{data.telegram.connected ? "Подключён" : "Можно подключить"}</strong></article></div><nav className="tabs">{([['today','Сегодня'],['plan','Мой маршрут'],['history','История'],['settings','Настройки']] as [Tab,string][]).map(([key,label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>{error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}
    {tab === "today" && <div className="dashboard-grid"><section className="card task-card"><p className="eyebrow">Один шаг сегодня</p>{data.task ? <><div className="section-heading"><h2>{data.task.title}</h2><span className={`badge ${data.task.status.toLowerCase()}`}>{statusLabels[data.task.status]}</span></div><p className="muted">{data.task.sphere}</p><div className="variants">{(["minimum", "normal", "expanded"] as Variant[]).map(v => <button key={v} disabled={busy} className={variant === v ? "selected" : ""} onClick={() => setVariant(v)}><strong>{labelForVariant(v)}</strong><span>{data.task!.variants[v]}</span></button>)}</div><label>Личная заметка <span className="muted">· организатору не показывается</span><textarea value={note} onChange={e => setNote(e.target.value)} maxLength={1500} /></label><div className="actions"><button className="primary" disabled={busy} onClick={() => report("COMPLETED")}>Выполнено</button><button className="secondary" disabled={busy} onClick={() => report("PARTIAL")}>Частично</button><button className="text-button" disabled={busy} onClick={() => report("SKIPPED")}>Пропустить</button></div></> : <><h2>{user.paused ? "Сейчас у вас пауза" : "Подготовим ваш маршрут"}</h2><button className="primary" onClick={() => setTab(user.paused ? "settings" : "plan")}>Открыть маршрут</button></>}</section><aside className="card"><p className="eyebrow">Ваше состояние</p><h2>Колесо баланса</h2><Wheel scores={user.scores} /><p className="muted">Заполнено {user.scores.filter(x => x !== null).length} из 12 сфер. Общего балла нет.</p><button className="secondary" onClick={() => setTab("plan")}>Посмотреть оценки</button></aside></div>}
    {tab === "plan" && <form onSubmit={saveProfile}><div className="dashboard-grid"><section className="card"><p className="eyebrow">Личный ориентир</p><h2>{user.onboarded ? "Ваш маршрут" : "Начните с трёх вопросов"}</h2><label>Как к вам обращаться?<input value={draft.name} required minLength={2} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label>{starterQuestions.map((q, i) => <label key={q}>{q}<textarea value={draft.answers[i]} onChange={e => setDraft({ ...draft, answers: draft.answers.map((x, j) => i === j ? e.target.value : x) })} /></label>)}<label>Главная сфера<select value={draft.focus} onChange={e => setDraft({ ...draft, focus: e.target.value })}>{spheres.map(s => <option key={s}>{s}</option>)}</select></label><label>Моя цель на ближайший месяц<input maxLength={500} value={draft.goal} onChange={e => setDraft({ ...draft, goal: e.target.value })} /></label></section><section className="card"><h2>Как вы чувствуете себя сейчас?</h2><p className="muted">0 — совсем не устраивает, 10 — полностью устраивает. Можно оставить сферу без оценки.</p><Wheel scores={draft.scores} /><div className="score-list">{spheres.map((sphere, i) => <label key={sphere}><span>{i + 1}. {sphere}</span><select value={draft.scores[i] ?? ""} onChange={e => setDraft({ ...draft, scores: draft.scores.map((s, j) => i === j ? (e.target.value === "" ? null : Number(e.target.value)) : s) })}><option value="">Без оценки</option>{Array.from({ length: 11 }, (_, s) => <option key={s} value={s}>{s}</option>)}</select></label>)}</div></section></div><div className="save-bar"><span className="muted">Личные ответы и оценки видны только вам.</span><button className="primary" disabled={busy}>{busy ? "Сохраняем…" : "Сохранить маршрут"}</button></div></form>}
    {tab === "history" && <><section className="card"><div className="section-heading"><h2>История шагов</h2><span className="muted">Последние 60 задач</span></div>{data.history.length ? <div className="table-scroll"><table><thead><tr><th>Дата</th><th>Задача</th><th>Результат</th><th>Личная заметка</th></tr></thead><tbody>{data.history.map(t => <tr key={t.id}><td>{t.localDate}</td><td>{t.title}<small>{t.sphere}</small></td><td><span className={`badge ${t.status.toLowerCase()}`}>{statusLabels[t.status]}</span></td><td>{t.note || "—"}</td></tr>)}</tbody></table></div> : <p className="muted">Здесь появятся ваши задачи после сохранения маршрута.</p>}</section><section className="card spaced"><button className="secondary" disabled={busy} onClick={() => action(() => requestJson("/api/snapshots", "POST", {}), "Снимок сохранён.")}>Сохранить снимок колеса</button>{data.snapshots.map(s => <details key={s.id}><summary>{new Date(s.created_at).toLocaleString("ru")}</summary><ul>{spheres.map((name, i) => <li key={name}>{name}: {s.scores[i] ?? "Без оценки"}</li>)}</ul></details>)}</section></>}
    {tab === "settings" && <div className="dashboard-grid"><section className="card"><p className="eyebrow">Вы управляете связью</p><h2>Подключение Telegram</h2><p>Откройте бота, нажмите «Запустить», затем подтвердите связь в этом кабинете.</p>{data.telegram.connected ? <><p className="success">Telegram подключён.</p><button className="secondary" disabled={busy} onClick={() => action(() => requestJson("/api/telegram/link", "DELETE", {}), "Telegram отключён.")}>Отключить</button></> : !data.telegram.available ? <p className="notice">Организатор ещё настраивает бота. Веб-кабинет уже работает.</p> : <><button className="primary" disabled={busy} onClick={() => action(async () => { const r = await requestJson<{ url: string }>("/api/telegram/link", "POST", {}); setTelegramUrl(r.url); }, "Ссылка действует 10 минут.")}>Создать ссылку подключения</button>{telegramUrl && <p><a className="button secondary" href={telegramUrl} target="_blank" rel="noopener noreferrer">Открыть Telegram ↗</a></p>}{data.telegram.pending && <div className="notice"><p>В боте откликнулся: <strong>{data.telegram.pending.candidate_name}</strong>.</p><button className="primary" disabled={busy} onClick={() => action(() => requestJson("/api/telegram/confirm", "POST", {}), "Telegram подключён.")}>Это мой Telegram — подтвердить</button></div>}</>}<hr /><h2>Темп программы</h2><button className="secondary" disabled={busy} onClick={() => action(() => requestJson("/api/me", "PATCH", { ...profile(user), paused: !user.paused }), user.paused ? "Пауза снята." : "Пауза включена.")}>{user.paused ? "Продолжить программу" : "Поставить на паузу"}</button></section><section className="card"><h2>Ваши данные</h2><p>{user.email}</p><a className="button secondary" href="/api/data/export">Скачать мои данные</a><hr /><details><summary className="danger-text">Удаление аккаунта</summary><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await requestJson("/api/data/delete", "POST", { password: f.get("password"), confirmation: f.get("confirmation") }); router.push("/"); router.refresh(); } catch (err) { setError((err as Error).message); } }}><label>Текущий пароль<input name="password" type="password" required /></label><label>Напишите УДАЛИТЬ<input name="confirmation" required pattern="УДАЛИТЬ" /></label><button className="danger">Удалить аккаунт</button></form></details></section></div>}
  </main></>;
}
